version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: warehouse-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
    container_name: warehouse-frontend
    restart: unless-stopped
    ports:
      - "8000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001/api/v1
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: warehouse-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_pass
      POSTGRES_DB: warehouse_db
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: warehouse-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db-data:
